In [4]:
import sys
!{sys.executable} -m pip install numpy
import numpy as np
!{sys.executable} -m pip install scipy
from scipy.special import softmax

# Define word embeddings (simulated for simplicity)
word_embeddings = np.array([
    [1, 0, 0],  # Word 1
    [0, 1, 0],  # Word 2
    [1, 1, 0],  # Word 3
    [0, 0, 1]   # Word 4
])

# Randomly generate weights for Query (Q), Key (K), and Value (V) matrices
np.random.seed(42)
W_Q = np.random.randint(5, size=(3, 3))
W_K = np.random.randint(5, size=(3, 3))
W_V = np.random.randint(5, size=(3, 3))

# Compute queries, keys, values
Q = np.dot(word_embeddings, W_Q)
K = np.dot(word_embeddings, W_K)
V = np.dot(word_embeddings, W_V)

# Calculate attention scores
attention_scores = np.dot(Q, K.T)
attention_weights = softmax(attention_scores, axis=1)

# Compute the attention output
attention_output = np.dot(attention_weights, V)

print("Attention Weights:\n", attention_weights)
print("Attention Output:\n", attention_output)


Attention Weights:
 [[2.78946809e-10 6.91440010e-13 1.00000000e+00 1.87952882e-12]
 [1.02618796e-10 9.35762297e-14 1.00000000e+00 4.65888614e-15]
 [2.86251858e-20 6.47023493e-26 1.00000000e+00 8.75651076e-27]
 [1.12535159e-07 1.52299776e-08 9.99999857e-01 1.52299776e-08]]
Attention Output:
 [[4.         6.         1.        ]
 [4.         6.         1.        ]
 [4.         6.         1.        ]
 [3.99999949 5.99999956 1.        ]]



[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip
